os: linux
dist: focal

language: ruby

rvm:
  - '2.5.0'

script: "bundle exec rspec spec/"

gemfile:
  - Gemfile
before_install:
  - sudo apt-get install libx265-dev libde265-dev libheif-dev libvips-dev 
